name: バグ報告
description: 改善のためのレポートを作成する

body:
  - type: textarea
    id: description
    attributes:
      label: バグの内容
      placeholder: |
        バグが何かを明確かつ簡潔に記載してください
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: 再現手順
      placeholder: |
        1. 『...』へ移動する
        2. 『....』をクリックする
        3. 『....』までスクロールする
        4. エラーが発生する
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      placeholder: |
        本来どうなることを期待していたか、明確かつ簡潔に記載してください

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      placeholder: |
        該当する場合は、問題を説明するためのスクリーンショットを添付してください

  - type: textarea
    id: environment-desktop
    attributes:
      label: このバグを発見した環境を記載してください(デスクトップ)
      placeholder: |
        OS: [例: iOS]
        ブラウザ: [例: Chrome, Safari]
        バージョン: [例: 22]

  - type: textarea
    id: environment-smartphone
    attributes:
      label: このバグを発見した環境を記載してください(スマートフォン)
      placeholder: |
        デバイス: [例: iPhone6]
        OS: [例: iOS8.1]
        ブラウザ: [例: 標準ブラウザ, Safari]
        バージョン: [例: 22]

  - type: textarea
    id: other
    attributes:
      label: 追加情報
      placeholder: |
        この問題に関するその他の情報があれば記載してください
