name: 機能リクエスト
description: このプロジェクトへのアイデアを提案する

body:
  - type: textarea
    id: description
    attributes:
      label: この機能リクエストは何か問題に関連していますか？具体的に説明してください
      render: true
      placeholder: |
        その問題が何であるか、明確かつ簡潔に説明してください。例：いつも○○にイライラしています
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 希望する解決策の提案を記載してください
      render: true
      placeholder: |
        どのようになってほしいのか、明確かつ簡潔に説明してください
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: 検討した代替案について説明してください
      render: true
      placeholder: |
        検討した他の解決策や機能について、明確かつ簡潔に説明してください

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      render: true
      placeholder: |
        この機能リクエストに関するその他の情報やスクリーンショットがあれば記載してください
